// Bundled reference catalog — mirrors supabase/seed.sql row-for-row. This is
// the exact data the storefront renders whenever no Supabase project is
// connected yet (see lib/supabase/env.ts#isSupabaseConfigured), so the site
// is fully browsable during setup and so local development never needs a
// live database. Every "Supabase equivalent" query in lib/data/*.ts falls
// back to a filter/sort over these arrays.
//
// IMPORTANT: this is seed/reference data, not a permanent catalog. Once a
// project is connected, every value here becomes admin-editable and this
// file stops being read.

import type {
  Category,
  Comparison,
  Faq,
  Guide,
  Product,
  ProductVariation,
  Provider,
  ProviderCategoryPage,
  Review,
  SiteSettings,
  UseCase,
} from "./types";

const now = "2026-01-01T00:00:00.000Z";

// ---------------------------------------------------------------------------
// Providers
// ---------------------------------------------------------------------------

export const mockProviders: Provider[] = [
  {
    id: "aws",
    name: "Amazon Web Services",
    slug: "aws",
    description: "Compute, storage, credits and AI/ML infrastructure on the world's most widely adopted cloud platform.",
    logo_url: null,
    website_url: "https://aws.amazon.com",
    is_active: true,
    sort_order: 1,
    seo_title: "AWS Cloud Accounts, Credits & AI Cloud | GoCloudShop",
    seo_description: "Browse AWS compute accounts, cloud credits and AI-ready accounts with transparent pricing.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "google-cloud",
    name: "Google Cloud",
    slug: "google-cloud",
    description: "Cloud credits and AI/ML-ready infrastructure on Google Cloud Platform.",
    logo_url: null,
    website_url: "https://cloud.google.com",
    is_active: true,
    sort_order: 2,
    seo_title: "Google Cloud Accounts & Credits | GoCloudShop",
    seo_description: "Explore Google Cloud credit packages and AI-ready infrastructure with clear pricing.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "azure",
    name: "Microsoft Azure",
    slug: "azure",
    description: "Free trial, pay-as-you-go and cloud credit accounts on Microsoft Azure.",
    logo_url: null,
    website_url: "https://azure.microsoft.com",
    is_active: true,
    sort_order: 3,
    seo_title: "Microsoft Azure Cloud Accounts & Credits | GoCloudShop",
    seo_description: "Browse Azure free trial, PAYG and cloud credit accounts with transparent pricing.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "digitalocean",
    name: "DigitalOcean",
    slug: "digitalocean",
    description: "Developer-friendly compute accounts, from starter droplets to high-capacity infrastructure.",
    logo_url: null,
    website_url: "https://www.digitalocean.com",
    is_active: true,
    sort_order: 4,
    seo_title: "DigitalOcean Cloud Accounts | GoCloudShop",
    seo_description: "Browse DigitalOcean droplet-capacity accounts with transparent pricing and specifications.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "oracle-cloud",
    name: "Oracle Cloud",
    slug: "oracle-cloud",
    description: "Oracle Cloud Infrastructure credits and established/upgraded account tiers.",
    logo_url: null,
    website_url: "https://www.oracle.com/cloud/",
    is_active: true,
    sort_order: 5,
    seo_title: "Oracle Cloud Accounts & Credits | GoCloudShop",
    seo_description: "Explore Oracle Cloud Infrastructure credit and account options with clear pricing.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "linode",
    name: "Linode",
    slug: "linode",
    description: "Akamai's Linode cloud credits and specialized infrastructure accounts.",
    logo_url: null,
    website_url: "https://www.linode.com",
    is_active: true,
    sort_order: 6,
    seo_title: "Linode Cloud Accounts & Credits | GoCloudShop",
    seo_description: "Browse Linode cloud credit packages and specialized account configurations.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "ibm-cloud",
    name: "IBM Cloud",
    slug: "ibm-cloud",
    description: "IBM Cloud free trial and standard accounts, including Watson AI and Kubernetes access.",
    logo_url: null,
    website_url: "https://www.ibm.com/cloud",
    is_active: true,
    sort_order: 7,
    seo_title: "IBM Cloud Accounts | GoCloudShop",
    seo_description: "Explore IBM Cloud free trial and standard account options with transparent pricing.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "kamatera",
    name: "Kamatera",
    slug: "kamatera",
    description: "Pay-per-second cloud infrastructure across multiple global datacenters.",
    logo_url: null,
    website_url: "https://www.kamatera.com",
    is_active: true,
    sort_order: 8,
    seo_title: "Kamatera Cloud Accounts | GoCloudShop",
    seo_description: "Browse Kamatera free trial and standard cloud account options.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "alibaba-cloud",
    name: "Alibaba Cloud",
    slug: "alibaba-cloud",
    description: "Personal and business cloud accounts with strong Asia-Pacific infrastructure coverage.",
    logo_url: null,
    website_url: "https://www.alibabacloud.com",
    is_active: true,
    sort_order: 9,
    seo_title: "Alibaba Cloud Accounts | GoCloudShop",
    seo_description: "Explore Alibaba Cloud personal and business account tiers with transparent pricing.",
    created_at: now,
    updated_at: now,
  },
  {
    id: "atlantic-net",
    name: "Atlantic.Net",
    slug: "atlantic-net",
    description: "HIPAA-compliant cloud hosting with a free trial entry point.",
    logo_url: null,
    website_url: "https://www.atlantic.net",
    is_active: true,
    sort_order: 10,
    seo_title: "Atlantic.Net Cloud Accounts | GoCloudShop",
    seo_description: "Browse Atlantic.Net free trial cloud account access.",
    created_at: now,
    updated_at: now,
  },
];

// ---------------------------------------------------------------------------
// Categories
// ---------------------------------------------------------------------------

export const mockCategories: Category[] = [
  {
    id: "cat-cloud-accounts",
    name: "Cloud Accounts",
    slug: "cloud-accounts",
    description: "Ready-to-use cloud accounts across every major provider.",
    image_url: null,
    icon: "Cloud",
    parent_id: null,
    seo_title: "Cloud Accounts | GoCloudShop",
    seo_description: "Browse cloud accounts from AWS, Google Cloud, Azure, DigitalOcean and more.",
    is_active: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-cloud-credits",
    name: "Cloud Credits",
    slug: "cloud-credits",
    description: "Prepaid cloud credit packages for AWS, Google Cloud, Azure, Oracle Cloud and Linode.",
    image_url: null,
    icon: "Coins",
    parent_id: null,
    seo_title: "Cloud Credits | GoCloudShop",
    seo_description: "Browse cloud credit packages across leading providers with transparent pricing.",
    is_active: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-ai-cloud",
    name: "AI Cloud",
    slug: "ai-cloud",
    description: "AI-ready cloud accounts built for development, experimentation and production AI workloads.",
    image_url: null,
    icon: "Sparkles",
    parent_id: null,
    seo_title: "AI Cloud Accounts | GoCloudShop",
    seo_description: "Explore AI-ready cloud accounts and AI/ML infrastructure with transparent pricing.",
    is_active: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-ai-ml",
    name: "AI/ML",
    slug: "ai-ml",
    description: "Infrastructure for machine learning development, training and inference.",
    image_url: null,
    icon: "BrainCircuit",
    parent_id: null,
    seo_title: "AI/ML Infrastructure | GoCloudShop",
    seo_description: "Browse AI and machine learning infrastructure products.",
    is_active: true,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-gpu-cloud",
    name: "GPU Cloud",
    slug: "gpu-cloud",
    description: "GPU-accelerated cloud infrastructure for AI, ML and high-performance workloads.",
    image_url: null,
    icon: "Cpu",
    parent_id: null,
    seo_title: "GPU Cloud | GoCloudShop",
    seo_description: "Explore GPU cloud infrastructure for AI training and inference.",
    is_active: true,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-compute",
    name: "Compute",
    slug: "compute",
    description: "Scalable compute accounts sized from lightweight to high-performance workloads.",
    image_url: null,
    icon: "Server",
    parent_id: null,
    seo_title: "Cloud Compute | GoCloudShop",
    seo_description: "Browse cloud compute accounts across vCPU tiers and providers.",
    is_active: true,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-free-trials",
    name: "Free Trials",
    slug: "free-trials",
    description: "Free trial cloud accounts to explore a provider's platform before committing.",
    image_url: null,
    icon: "Gift",
    parent_id: null,
    seo_title: "Free Trial Cloud Accounts | GoCloudShop",
    seo_description: "Explore free trial cloud accounts across supported providers.",
    is_active: true,
    sort_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-pay-as-you-go",
    name: "Pay-As-You-Go",
    slug: "pay-as-you-go",
    description: "Flexible, no-commitment billing accounts.",
    image_url: null,
    icon: "Wallet",
    parent_id: null,
    seo_title: "Pay-As-You-Go Cloud Accounts | GoCloudShop",
    seo_description: "Browse pay-as-you-go cloud accounts with no upfront commitment.",
    is_active: true,
    sort_order: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cat-enterprise",
    name: "Enterprise",
    slug: "enterprise",
    description: "Large-scale cloud and AI infrastructure for enterprise workloads.",
    image_url: null,
    icon: "Building2",
    parent_id: null,
    seo_title: "Enterprise Cloud & AI Infrastructure | GoCloudShop",
    seo_description: "Explore enterprise-scale cloud accounts, credits and AI infrastructure.",
    is_active: true,
    sort_order: 9,
    created_at: now,
    updated_at: now,
  },
];

function cat(slug: string): Category {
  return mockCategories.find((c) => c.slug === slug)!;
}
function prov(slug: string): Provider {
  return mockProviders.find((p) => p.slug === slug)!;
}

// ---------------------------------------------------------------------------
// Provider + category combo landing pages (/aws-accounts, /aws-credits, ...)
// ---------------------------------------------------------------------------

export const mockProviderCategoryPages: ProviderCategoryPage[] = [
  { id: "pcp-aws-accounts", slug: "aws-accounts", provider_id: "aws", category_id: "cat-cloud-accounts", product_type: null, title: "AWS Cloud Accounts", intro_content: "Compute-ready AWS accounts sized by vCPU, plus free trial access.", seo_title: "Buy AWS Cloud Accounts | GoCloudShop", seo_description: "Browse AWS compute accounts and free trial access with transparent pricing.", is_active: true, sort_order: 1, created_at: now, updated_at: now },
  { id: "pcp-aws-credits", slug: "aws-credits", provider_id: "aws", category_id: "cat-cloud-credits", product_type: null, title: "AWS Cloud Credits", intro_content: "Prepaid AWS credit packages from $1K up to $100K.", seo_title: "Buy AWS Cloud Credits | GoCloudShop", seo_description: "Browse AWS credit packages from $1K to $100K with transparent pricing.", is_active: true, sort_order: 2, created_at: now, updated_at: now },
  { id: "pcp-aws-ai", slug: "aws-ai", provider_id: "aws", category_id: "cat-ai-cloud", product_type: null, title: "AWS AI Cloud", intro_content: "AI-enabled AWS accounts across compute tiers, from starter to enterprise-scale.", seo_title: "AWS AI Cloud Accounts | GoCloudShop", seo_description: "Explore AI-enabled AWS cloud accounts with transparent pricing and specifications.", is_active: true, sort_order: 3, created_at: now, updated_at: now },
  { id: "pcp-google-cloud-accounts", slug: "google-cloud-accounts", provider_id: "google-cloud", category_id: "cat-cloud-accounts", product_type: null, title: "Google Cloud Accounts", intro_content: "Google Cloud account access backed by credit packages.", seo_title: "Buy Google Cloud Accounts | GoCloudShop", seo_description: "Browse Google Cloud account and credit options with transparent pricing.", is_active: true, sort_order: 4, created_at: now, updated_at: now },
  { id: "pcp-google-cloud-credits", slug: "google-cloud-credits", provider_id: "google-cloud", category_id: "cat-cloud-credits", product_type: null, title: "Google Cloud Credits", intro_content: "Google Cloud credit packages from $300 up to $25K.", seo_title: "Buy Google Cloud Credits | GoCloudShop", seo_description: "Browse Google Cloud credit packages with transparent pricing.", is_active: true, sort_order: 5, created_at: now, updated_at: now },
  { id: "pcp-google-cloud-ai", slug: "google-cloud-ai", provider_id: "google-cloud", category_id: "cat-ai-cloud", product_type: null, title: "Google Cloud AI", intro_content: "Vertex AI-ready Google Cloud credit and infrastructure options.", seo_title: "Google Cloud AI | GoCloudShop", seo_description: "Explore Vertex AI-ready Google Cloud infrastructure with transparent pricing.", is_active: true, sort_order: 6, created_at: now, updated_at: now },
  { id: "pcp-azure-accounts", slug: "azure-accounts", provider_id: "azure", category_id: "cat-cloud-accounts", product_type: null, title: "Azure Cloud Accounts", intro_content: "Azure free trial and pay-as-you-go account access.", seo_title: "Buy Azure Cloud Accounts | GoCloudShop", seo_description: "Browse Azure free trial and PAYG accounts with transparent pricing.", is_active: true, sort_order: 7, created_at: now, updated_at: now },
  { id: "pcp-azure-credits", slug: "azure-credits", provider_id: "azure", category_id: "cat-cloud-credits", product_type: null, title: "Azure Cloud Credits", intro_content: "Azure credit packages from $1K up to $25K.", seo_title: "Buy Azure Cloud Credits | GoCloudShop", seo_description: "Browse Azure credit packages with transparent pricing.", is_active: true, sort_order: 8, created_at: now, updated_at: now },
  { id: "pcp-azure-ai", slug: "azure-ai", provider_id: "azure", category_id: "cat-ai-cloud", product_type: null, title: "Azure AI", intro_content: "AI-ready Azure infrastructure and credit options.", seo_title: "Azure AI Cloud | GoCloudShop", seo_description: "Explore AI-ready Azure infrastructure with transparent pricing.", is_active: true, sort_order: 9, created_at: now, updated_at: now },
  { id: "pcp-digitalocean-accounts", slug: "digitalocean-accounts", provider_id: "digitalocean", category_id: "cat-cloud-accounts", product_type: null, title: "DigitalOcean Accounts", intro_content: "DigitalOcean droplet-capacity accounts from starter to high-scale.", seo_title: "Buy DigitalOcean Accounts | GoCloudShop", seo_description: "Browse DigitalOcean accounts with transparent pricing and droplet capacity.", is_active: true, sort_order: 10, created_at: now, updated_at: now },
  { id: "pcp-oracle-cloud-accounts", slug: "oracle-cloud-accounts", provider_id: "oracle-cloud", category_id: "cat-cloud-accounts", product_type: null, title: "Oracle Cloud Accounts", intro_content: "Oracle Cloud Infrastructure accounts and credit packages.", seo_title: "Buy Oracle Cloud Accounts | GoCloudShop", seo_description: "Browse Oracle Cloud accounts and credits with transparent pricing.", is_active: true, sort_order: 11, created_at: now, updated_at: now },
  { id: "pcp-linode-accounts", slug: "linode-accounts", provider_id: "linode", category_id: "cat-cloud-accounts", product_type: null, title: "Linode Accounts", intro_content: "Linode credit packages and specialized account configurations.", seo_title: "Buy Linode Accounts | GoCloudShop", seo_description: "Browse Linode accounts and credits with transparent pricing.", is_active: true, sort_order: 12, created_at: now, updated_at: now },
];

// ---------------------------------------------------------------------------
// Products + variations
// ---------------------------------------------------------------------------

function variation(
  productId: string,
  overrides: Partial<ProductVariation> & Pick<ProductVariation, "name" | "slug" | "price">
): ProductVariation {
  return {
    id: `${productId}--${overrides.slug}`,
    product_id: productId,
    description: null,
    currency: "USD",
    features: [],
    specifications: {},
    region: "Worldwide",
    availability: "in_stock",
    delivery_time_text: "Within 24 hours",
    image_url: null,
    badge: null,
    ai_category: null,
    ai_platform: null,
    gpu_type: null,
    gpu_count: null,
    vram: null,
    compute_type: null,
    model_support: null,
    architecture: null,
    ai_services: [],
    inference_support: null,
    training_support: null,
    sort_order: 0,
    is_active: true,
    created_at: now,
    updated_at: now,
    ...overrides,
  };
}

function baseProduct(overrides: Partial<Product> & Pick<Product, "id" | "name" | "slug" | "provider_id" | "category_id" | "product_type">): Product {
  return {
    description: null,
    short_description: null,
    base_price: null,
    currency: "USD",
    features: [],
    whats_included: [
      "Account / package access",
      "Applicable cloud services",
      "Selected resources",
      "Dashboard access",
      "Customer support",
    ],
    specifications: {},
    image_url: null,
    provider_logo_override_url: null,
    region: "Worldwide",
    availability: "in_stock",
    delivery_time_text: "Within 24 hours",
    support_type: "Telegram support",
    replacement_policy: "Replacement available for non-working accounts reported within 24 hours of delivery.",
    refund_policy: "Refunds are considered case-by-case before delivery; see our Refund Policy for details.",
    badge: null,
    is_featured: false,
    is_popular: false,
    is_ai: false,
    is_gpu: false,
    is_active: true,
    sort_order: 0,
    seo_title: null,
    seo_description: null,
    og_image_url: null,
    created_at: now,
    updated_at: now,
    ...overrides,
  };
}

export const mockProducts: Product[] = [
  // ---- AWS -----------------------------------------------------------
  baseProduct({
    id: "p-aws-starter",
    name: "AWS Starter / Free Trial",
    slug: "aws-starter-free-trial",
    provider_id: "aws",
    category_id: "cat-free-trials",
    product_type: "Free Trial",
    base_price: 18,
    short_description: "Entry-level AWS account access to explore the platform.",
    description: "An entry-level AWS account for developers who want to explore core AWS services before scaling up.",
    delivery_time_text: "Within 24 hours",
  }),
  baseProduct({
    id: "p-aws-compute",
    name: "AWS Compute Accounts",
    slug: "aws-compute-accounts",
    provider_id: "aws",
    category_id: "cat-compute",
    product_type: "Compute",
    short_description: "AWS compute accounts sized from 8 to 512 vCPU.",
    description: "AWS accounts configured for compute workloads, available across six vCPU tiers to match your project's scale.",
    is_popular: true,
    is_featured: true,
  }),
  baseProduct({
    id: "p-aws-credits",
    name: "AWS Cloud Credits",
    slug: "aws-cloud-credits",
    provider_id: "aws",
    category_id: "cat-cloud-credits",
    product_type: "Cloud Credit",
    short_description: "Prepaid AWS credit packages from $1K to $100K.",
    description: "Prepaid AWS cloud credit packages for global-scale usage across the AWS platform, from small projects to enterprise billing environments.",
    is_featured: true,
  }),
  baseProduct({
    id: "p-aws-ai-10rpm",
    name: "AWS AI Account — 10 RPM | 32 vCPU | AI Enabled",
    slug: "aws-ai-account-10rpm-32vcpu",
    provider_id: "aws",
    category_id: "cat-ai-cloud",
    product_type: "AI Cloud Account",
    base_price: 75,
    badge: "AI Ready",
    is_ai: true,
    is_featured: true,
    short_description: "AI-enabled AWS account with 32 vCPU and 10 RPM capacity.",
    description: "An AI-enabled AWS account suitable for AI workloads, with 32 vCPU of compute and 10 requests-per-minute capacity.",
  }),
  baseProduct({
    id: "p-aws-ai-50rpm-kiro",
    name: "AWS AI Account — 50 RPM | Kiro Working | 32 vCPU | AI Enabled",
    slug: "aws-ai-account-50rpm-kiro-32vcpu",
    provider_id: "aws",
    category_id: "cat-ai-cloud",
    product_type: "AI Cloud Account",
    base_price: 199,
    badge: "AI + Kiro",
    is_ai: true,
    short_description: "AI development account with working Kiro access and 32 vCPU.",
    description: "An AI-enabled AWS account suitable for AI development workloads, with working Kiro access, 32 vCPU of compute and 50 requests-per-minute capacity.",
  }),
  baseProduct({
    id: "p-aws-ai-10krpm-5vcpu",
    name: "AWS AI Account — 10K RPM | 4.6 Support | 5 vCPU | Multi-Year Aged | AI Enabled",
    slug: "aws-ai-account-10krpm-5vcpu-aged",
    provider_id: "aws",
    category_id: "cat-ai-cloud",
    product_type: "Aged AI Cloud Account",
    base_price: 250,
    badge: "Aged AI",
    is_ai: true,
    short_description: "Multi-year aged AI-enabled AWS account with 10K RPM capacity.",
    description: "A multi-year aged AWS account, AI-enabled with 10,000 requests-per-minute capacity, 4.6 support rating and 5 vCPU of compute.",
  }),
  baseProduct({
    id: "p-aws-ai-10krpm-96vcpu",
    name: "AWS AI Account — 10K RPM | 4.6 Support | 96 vCPU | Multi-Year Aged | AI Enabled",
    slug: "aws-ai-account-10krpm-96vcpu-aged",
    provider_id: "aws",
    category_id: "cat-ai-cloud",
    product_type: "Aged AI Cloud Account",
    base_price: 399,
    badge: "High Compute",
    is_ai: true,
    short_description: "High-compute multi-year aged AI-enabled AWS account, 96 vCPU.",
    description: "A multi-year aged, high-performance-compute AWS account, AI-enabled with 10,000 requests-per-minute capacity, 4.6 support rating and 96 vCPU of compute.",
  }),
  baseProduct({
    id: "p-aws-ai-10krpm-128vcpu",
    name: "AWS AI Account — 10K RPM | 4.6 Support | 128 vCPU | Multi-Year Aged | AI Enabled",
    slug: "aws-ai-account-10krpm-128vcpu-aged",
    provider_id: "aws",
    category_id: "cat-ai-cloud",
    product_type: "Aged AI Cloud Account",
    base_price: 899,
    badge: "Premium AI",
    is_ai: true,
    short_description: "Premium multi-year aged AI-enabled AWS account, 128 vCPU.",
    description: "A multi-year aged, high-performance-compute AWS account, AI-enabled with 10,000 requests-per-minute capacity, 4.6 support rating and 128 vCPU of compute.",
  }),
  baseProduct({
    id: "p-aws-ai-10krpm-256vcpu",
    name: "AWS AI Account — 10K RPM | 4.6 Support | 256 vCPU | Multi-Year Aged | AI Enabled",
    slug: "aws-ai-account-10krpm-256vcpu-aged",
    provider_id: "aws",
    category_id: "cat-ai-cloud",
    product_type: "Aged AI Cloud Account",
    base_price: 999,
    badge: "Ultimate AI",
    is_ai: true,
    is_featured: true,
    short_description: "Large-scale multi-year aged AI-enabled AWS account, 256 vCPU.",
    description: "A multi-year aged AWS account built for large-scale AI workloads: AI-enabled, 10,000 requests-per-minute capacity, 4.6 support rating and 256 vCPU of compute.",
  }),
  baseProduct({
    id: "p-aws-ai-enterprise-384vcpu",
    name: "AWS AI Account — Cloud Platform Working | 384 vCPU | Bedrock Not Included | AI Enabled",
    slug: "aws-ai-account-enterprise-384vcpu",
    provider_id: "aws",
    category_id: "cat-enterprise",
    product_type: "Enterprise AI Cloud Account",
    base_price: 3999,
    badge: "Enterprise AI",
    is_ai: true,
    short_description: "Enterprise-scale AI-enabled AWS account with 384 vCPU.",
    description: "An enterprise-scale AWS account for large-scale AI workloads: working cloud platform access, AI-enabled, 384 vCPU of compute. Amazon Bedrock is not included.",
  }),

  // ---- Google Cloud ----------------------------------------------------
  baseProduct({
    id: "p-gcp-credits",
    name: "Google Cloud Credits",
    slug: "google-cloud-credits",
    provider_id: "google-cloud",
    category_id: "cat-cloud-credits",
    product_type: "Cloud Credit",
    short_description: "Google Cloud credit packages from $300 to $25K.",
    description: "Prepaid Google Cloud Platform credit packages covering Compute Engine, Cloud Run, BigQuery, Vertex AI-ready infrastructure and more, depending on tier.",
    is_featured: true,
  }),

  // ---- Azure -------------------------------------------------------
  baseProduct({
    id: "p-azure-starter",
    name: "Azure Starter / Free Trial",
    slug: "azure-starter-free-trial",
    provider_id: "azure",
    category_id: "cat-free-trials",
    product_type: "Free Trial Cloud Account",
    base_price: 25,
    short_description: "Entry-level Azure account access to explore the platform.",
    description: "Azure portal access with applicable free Azure products and cloud services across supported regions.",
  }),
  baseProduct({
    id: "p-azure-payg",
    name: "Azure Pay As You Go",
    slug: "azure-pay-as-you-go",
    provider_id: "azure",
    category_id: "cat-pay-as-you-go",
    product_type: "PAYG Cloud Account",
    base_price: 30,
    short_description: "Azure account with pay-as-you-go billing and no upfront commitment.",
    description: "An Azure account configured for pay-as-you-go billing across Azure services, with no upfront commitment required.",
  }),
  baseProduct({
    id: "p-azure-credits",
    name: "Azure Cloud Credits",
    slug: "azure-cloud-credits",
    provider_id: "azure",
    category_id: "cat-cloud-credits",
    product_type: "Cloud Credit",
    short_description: "Azure credit packages from $1K to $25K.",
    description: "Prepaid Microsoft Azure credit packages covering Virtual Machines, Storage, AI services and enterprise-grade Azure infrastructure, depending on tier.",
    is_featured: true,
  }),

  // ---- DigitalOcean --------------------------------------------------
  baseProduct({
    id: "p-do-compute",
    name: "DigitalOcean Compute Accounts",
    slug: "digitalocean-compute-accounts",
    provider_id: "digitalocean",
    category_id: "cat-compute",
    product_type: "Cloud Compute Account",
    short_description: "DigitalOcean accounts with 3 or 10 droplet capacity.",
    description: "DigitalOcean accounts configured with standard networking and cloud infrastructure, available in 3- or 10-droplet capacity.",
  }),
  baseProduct({
    id: "p-do-open25",
    name: "DigitalOcean Open 25 Port Accounts",
    slug: "digitalocean-open-25-port-accounts",
    provider_id: "digitalocean",
    category_id: "cat-cloud-accounts",
    product_type: "Advanced Cloud Account",
    short_description: "DigitalOcean accounts with port 25 open, from 10 to 500 droplet capacity.",
    description: "Advanced DigitalOcean accounts with expanded networking configuration (port 25 open), available across four droplet-capacity tiers.",
    is_featured: true,
  }),

  // ---- Oracle Cloud ----------------------------------------------------
  baseProduct({
    id: "p-oracle-credit",
    name: "Oracle Cloud $300 Credit",
    slug: "oracle-cloud-300-credit",
    provider_id: "oracle-cloud",
    category_id: "cat-cloud-credits",
    product_type: "Cloud Credit",
    base_price: 49,
    short_description: "$300 Oracle Cloud Infrastructure credit package.",
    description: "A $300 OCI credit package covering Oracle Cloud Infrastructure services and applicable Always Free resources.",
  }),
  baseProduct({
    id: "p-oracle-aged",
    name: "Oracle Aged Account",
    slug: "oracle-aged-account",
    provider_id: "oracle-cloud",
    category_id: "cat-cloud-accounts",
    product_type: "Cloud Account",
    base_price: 75,
    short_description: "Oracle Cloud account with established account history.",
    description: "An Oracle Cloud account with established account history and applicable account capabilities within the Oracle Cloud environment.",
  }),
  baseProduct({
    id: "p-oracle-upgraded",
    name: "Oracle Upgraded Account",
    slug: "oracle-upgraded-account",
    provider_id: "oracle-cloud",
    category_id: "cat-cloud-accounts",
    product_type: "Upgraded Cloud Account",
    base_price: 90,
    short_description: "Oracle Cloud account with an upgraded tier and higher limits.",
    description: "An upgraded-tier Oracle Cloud account with higher applicable limits and pay-as-you-go capability where applicable.",
  }),

  // ---- Linode ------------------------------------------------------
  baseProduct({
    id: "p-linode-credit",
    name: "Linode $100 Credit",
    slug: "linode-100-credit",
    provider_id: "linode",
    category_id: "cat-cloud-credits",
    product_type: "Cloud Credit",
    base_price: 25,
    short_description: "$100 Linode credit for global cloud infrastructure.",
    description: "A $100 Linode credit covering global regions and applicable cloud compute infrastructure and services.",
  }),
  baseProduct({
    id: "p-linode-port25",
    name: "Linode Account — Port 25 Open",
    slug: "linode-account-port-25-open",
    provider_id: "linode",
    category_id: "cat-cloud-accounts",
    product_type: "Cloud Account",
    base_price: 90,
    badge: "Port 25 Open",
    short_description: "Linode account configured for email/SMTP infrastructure.",
    description: "A Linode account with port 25 configuration for email server infrastructure, plus full applicable cloud access.",
  }),

  // ---- IBM Cloud -----------------------------------------------------
  baseProduct({
    id: "p-ibm-trial",
    name: "IBM Cloud Free Trial",
    slug: "ibm-cloud-free-trial",
    provider_id: "ibm-cloud",
    category_id: "cat-free-trials",
    product_type: "Free Trial Cloud Account",
    base_price: 30,
    short_description: "IBM Cloud account with Watson AI, IoT and Kubernetes access.",
    description: "An IBM Cloud environment account with access to Watson AI, IoT, Kubernetes and OpenShift services.",
  }),
  baseProduct({
    id: "p-ibm-port25",
    name: "IBM Cloud Port 25 Open",
    slug: "ibm-cloud-port-25-open",
    provider_id: "ibm-cloud",
    category_id: "cat-cloud-accounts",
    product_type: "Cloud Account",
    base_price: 70,
    badge: "Port 25 Open",
    short_description: "IBM Cloud account configured for email infrastructure.",
    description: "An IBM Cloud account with port 25 configuration for email infrastructure, plus applicable IBM Cloud platform access.",
  }),

  // ---- Kamatera ------------------------------------------------------
  baseProduct({
    id: "p-kamatera-trial",
    name: "Kamatera Free Trial",
    slug: "kamatera-free-trial",
    provider_id: "kamatera",
    category_id: "cat-free-trials",
    product_type: "Free Trial Cloud Account",
    base_price: 25,
    short_description: "Free trial Kamatera package across multiple datacenters.",
    description: "A free trial Kamatera package with access to cloud infrastructure, multiple datacenter options and pay-per-second billing.",
  }),
  baseProduct({
    id: "p-kamatera-port25",
    name: "Kamatera Port 25 Open",
    slug: "kamatera-port-25-open",
    provider_id: "kamatera",
    category_id: "cat-cloud-accounts",
    product_type: "Cloud Account",
    base_price: 35,
    badge: "Port 25 Open",
    short_description: "Kamatera account configured for email infrastructure.",
    description: "A Kamatera account with port 25 configuration for email infrastructure, cloud access and applicable datacenter options.",
  }),

  // ---- Alibaba Cloud ---------------------------------------------------
  baseProduct({
    id: "p-alibaba-personal",
    name: "Alibaba Cloud Personal",
    slug: "alibaba-cloud-personal",
    provider_id: "alibaba-cloud",
    category_id: "cat-cloud-accounts",
    product_type: "Cloud Account",
    base_price: 60,
    short_description: "Personal Alibaba Cloud account with ECS, OSS and RDS access.",
    description: "A personal Alibaba Cloud environment with ECS, OSS, RDS and Asia-Pacific infrastructure access.",
  }),
  baseProduct({
    id: "p-alibaba-business",
    name: "Alibaba Cloud Business",
    slug: "alibaba-cloud-business",
    provider_id: "alibaba-cloud",
    category_id: "cat-cloud-accounts",
    product_type: "Business Cloud Account",
    base_price: 100,
    short_description: "Business-oriented Alibaba Cloud account with ECS, OSS and RDS.",
    description: "A business-oriented Alibaba Cloud account with ECS, OSS, RDS and broader Alibaba Cloud service access.",
  }),

  // ---- Atlantic.Net ------------------------------------------------
  baseProduct({
    id: "p-atlanticnet-trial",
    name: "Atlantic.Net Free Trial",
    slug: "atlantic-net-free-trial",
    provider_id: "atlantic-net",
    category_id: "cat-free-trials",
    product_type: "Free Trial Cloud Account",
    base_price: 30,
    short_description: "Free trial Atlantic.Net cloud account access.",
    description: "A free trial Atlantic.Net environment with cloud infrastructure access and regional availability.",
  }),
];

export const mockVariations: ProductVariation[] = [
  // AWS Compute Accounts
  variation("p-aws-compute", { name: "8 vCPU", slug: "8-vcpu", price: 20, specifications: { vCPU: "8" }, sort_order: 1 }),
  variation("p-aws-compute", { name: "32 vCPU", slug: "32-vcpu", price: 30, specifications: { vCPU: "32" }, sort_order: 2, badge: "Popular" }),
  variation("p-aws-compute", { name: "64 vCPU", slug: "64-vcpu", price: 50, specifications: { vCPU: "64" }, sort_order: 3 }),
  variation("p-aws-compute", { name: "128 vCPU", slug: "128-vcpu", price: 120, specifications: { vCPU: "128" }, sort_order: 4 }),
  variation("p-aws-compute", { name: "256 vCPU", slug: "256-vcpu", price: 220, specifications: { vCPU: "256" }, sort_order: 5, badge: "High Compute" }),
  variation("p-aws-compute", { name: "512 vCPU", slug: "512-vcpu", price: 350, specifications: { vCPU: "512" }, sort_order: 6, badge: "High Compute" }),

  // AWS Cloud Credits
  variation("p-aws-credits", { name: "$1K Credit", slug: "1k-credit", price: 220, specifications: { "Credit Amount": "$1,000" }, sort_order: 1 }),
  variation("p-aws-credits", { name: "$5K Credit", slug: "5k-credit", price: 850, specifications: { "Credit Amount": "$5,000" }, sort_order: 2 }),
  variation("p-aws-credits", { name: "$10K Credit", slug: "10k-credit", price: 1699, specifications: { "Credit Amount": "$10,000" }, sort_order: 3 }),
  variation("p-aws-credits", { name: "$25K Credit", slug: "25k-credit", price: 3299, specifications: { "Credit Amount": "$25,000" }, sort_order: 4 }),
  variation("p-aws-credits", { name: "$50K Credit", slug: "50k-credit", price: 6999, specifications: { "Credit Amount": "$50,000" }, sort_order: 5 }),
  variation("p-aws-credits", {
    name: "$100K Credit",
    slug: "100k-credit",
    price: 12500,
    badge: "Ultimate",
    description: "Enterprise Cloud Credit — large-scale cloud usage with an enterprise billing environment and global region support.",
    features: [
      "$100,000 credit package",
      "Large-scale cloud usage",
      "Enterprise billing environment",
      "Global region support",
    ],
    specifications: { "Credit Amount": "$100,000", Type: "Enterprise Cloud Credit" },
    sort_order: 6,
  }),

  // Google Cloud Credits
  variation("p-gcp-credits", { name: "$300 Credit", slug: "300-credit", price: 55, specifications: { "Credit Amount": "$300" }, features: ["$300 GCP credits", "Compute Engine", "Cloud Run", "Google Cloud services", "Global regions"], sort_order: 1 }),
  variation("p-gcp-credits", { name: "$400 Credit", slug: "400-credit", price: 70, specifications: { "Credit Amount": "$400" }, features: ["$400 GCP credits", "Cloud Storage", "BigQuery", "Applicable Google Cloud services"], sort_order: 2 }),
  variation("p-gcp-credits", { name: "$1K Credit", slug: "1k-credit", price: 220, badge: "Popular", specifications: { "Credit Amount": "$1,000", Type: "AI / Cloud Credit" }, features: ["$1,000 GCP credits", "Compute", "Storage", "AI/ML", "Vertex AI-ready infrastructure"], sort_order: 3 }),
  variation("p-gcp-credits", { name: "$5K Credit", slug: "5k-credit", price: 599, badge: "Best Value", specifications: { "Credit Amount": "$5,000", Type: "Enterprise Cloud Credit" }, features: ["$5,000 GCP credits", "Full GCP platform access", "Enterprise-grade infrastructure", "Priority support where applicable"], sort_order: 4 }),
  variation("p-gcp-credits", { name: "$10K Credit", slug: "10k-credit", price: 1099, badge: "Enterprise", specifications: { "Credit Amount": "$10,000", Type: "Enterprise Cloud Credit" }, features: ["$10,000 GCP credits", "Broad Google Cloud services", "Large-scale workloads", "Applicable replacement/support policy"], sort_order: 5 }),
  variation("p-gcp-credits", { name: "$25K Credit", slug: "25k-credit", price: 1699, badge: "Pro", specifications: { "Credit Amount": "$25,000", Type: "Premium Cloud Credit" }, features: ["$25,000 GCP credit package", "Enterprise workloads", "AI/ML", "Dedicated support where applicable"], sort_order: 6 }),

  // Azure Cloud Credits
  variation("p-azure-credits", { name: "$1K Credit", slug: "1k-credit", price: 180, badge: "Popular", specifications: { "Credit Amount": "$1,000" }, features: ["$1,000 Azure credits", "Virtual Machines", "Storage", "AI services", "Azure regions"], sort_order: 1 }),
  variation("p-azure-credits", { name: "$5K Credit", slug: "5k-credit", price: 650, badge: "Hot", specifications: { "Credit Amount": "$5,000", Type: "Enterprise Cloud Credit" }, features: ["$5,000 Azure credits", "Enterprise-grade workloads", "Global Azure infrastructure"], sort_order: 2 }),
  variation("p-azure-credits", { name: "$25K Credit", slug: "25k-credit", price: 1750, badge: "Enterprise", specifications: { "Credit Amount": "$25,000", Type: "Enterprise Cloud Credit" }, features: ["$25,000 Azure credits", "Large-scale cloud usage", "Azure AI/services", "Enterprise infrastructure"], sort_order: 3 }),

  // DigitalOcean Compute Accounts
  variation("p-do-compute", { name: "3 Droplet", slug: "3-droplet", price: 25, specifications: { "Droplet Capacity": "3" }, features: ["3-unit compute capacity", "Standard networking", "Cloud infrastructure", "Applicable regions"], sort_order: 1 }),
  variation("p-do-compute", { name: "10 Droplet", slug: "10-droplet", price: 30, specifications: { "Droplet Capacity": "10" }, features: ["10-unit capacity", "Expanded compute", "Standard networking"], sort_order: 2 }),

  // DigitalOcean Open 25 Port Accounts
  variation("p-do-open25", { name: "10 Droplet", slug: "10-droplet", price: 299, specifications: { "Droplet Capacity": "10" }, features: ["3 compute capacity", "Expanded networking", "Applicable networking configuration"], sort_order: 1 }),
  variation("p-do-open25", { name: "25 Droplet", slug: "25-droplet", price: 699, specifications: { "Droplet Capacity": "25" }, features: ["25 compute capacity", "Expanded networking", "High-scale deployment"], sort_order: 2 }),
  variation("p-do-open25", { name: "100 Droplet", slug: "100-droplet", price: 2599, specifications: { "Droplet Capacity": "100" }, features: ["100 compute capacity", "Expanded networking", "Enterprise-oriented configuration"], sort_order: 3, badge: "Enterprise" }),
  variation("p-do-open25", { name: "500 Droplet", slug: "500-droplet", price: 7999, specifications: { "Droplet Capacity": "500" }, features: ["500 compute capacity", "Expanded networking", "Enterprise-oriented configuration"], sort_order: 4, badge: "Enterprise" }),
];

// Attach features to the single-variant / no-variant products' descriptions
// via product_type-appropriate feature lists where the spec provided them.
export const mockProductFeatures: Record<string, string[]> = {
  "p-aws-starter": ["AWS account access", "Applicable free-tier AWS services", "Cloud services", "AWS regions"],
  "p-aws-ai-10rpm": ["10 RPM", "32 vCPU", "AI Enabled", "AWS Cloud Platform", "Suitable for AI workloads"],
  "p-aws-ai-50rpm-kiro": ["50 RPM", "Kiro Working", "32 vCPU", "AI Enabled", "AWS Cloud Platform", "Suitable for AI development workloads"],
  "p-aws-ai-10krpm-5vcpu": ["10K RPM", "4.6 Support", "5 vCPU", "Multi-Year Aged", "AI Enabled", "AWS Cloud Platform"],
  "p-aws-ai-10krpm-96vcpu": ["10K RPM", "4.6 Support", "96 vCPU", "Multi-Year Aged", "AI Enabled", "AWS Cloud Platform", "High-performance compute"],
  "p-aws-ai-10krpm-128vcpu": ["10K RPM", "4.6 Support", "128 vCPU", "Multi-Year Aged", "AI Enabled", "AWS Cloud Platform", "High-performance compute"],
  "p-aws-ai-10krpm-256vcpu": ["10K RPM", "4.6 Support", "256 vCPU", "Multi-Year Aged", "AI Enabled", "AWS Cloud Platform", "High-performance compute", "Large-scale AI workloads"],
  "p-aws-ai-enterprise-384vcpu": ["Cloud Platform Working", "384 vCPU", "AI Enabled", "High-performance compute", "Enterprise-scale infrastructure", "Suitable for large-scale AI workloads", "Bedrock Not Included"],
  "p-azure-starter": ["Azure portal access", "Applicable free Azure products", "Cloud services", "Azure regions"],
  "p-azure-payg": ["Pay-as-you-go billing", "No upfront commitment", "Azure services", "Applicable regions"],
  "p-oracle-credit": ["$300 OCI credits", "OCI services", "Applicable Always Free resources"],
  "p-oracle-aged": ["Established account history", "Oracle Cloud environment", "Applicable account capabilities"],
  "p-oracle-upgraded": ["Higher applicable limits", "Upgraded account tier", "PAYG capability where applicable"],
  "p-linode-credit": ["$100 Linode credit", "Global regions", "Applicable cloud services", "Compute infrastructure"],
  "p-linode-port25": ["Port 25 configuration", "Email server infrastructure", "Full applicable cloud access"],
  "p-ibm-trial": ["IBM Cloud environment", "Watson AI", "IoT", "Kubernetes", "OpenShift"],
  "p-ibm-port25": ["Port 25 configuration", "Email infrastructure", "IBM Cloud services", "Applicable cloud platform access"],
  "p-kamatera-trial": ["Free trial package", "Cloud infrastructure", "Multiple datacenter options", "Pay-per-second infrastructure"],
  "p-kamatera-port25": ["Port 25 configuration", "Email infrastructure", "Cloud access", "Applicable datacenter options"],
  "p-alibaba-personal": ["ECS", "OSS", "RDS", "Asia-Pacific infrastructure", "Personal cloud environment"],
  "p-alibaba-business": ["Alibaba Cloud services", "ECS", "OSS", "RDS", "Business-oriented infrastructure"],
  "p-atlanticnet-trial": ["Free trial environment", "Cloud infrastructure", "Applicable server access", "Regional availability"],
};

for (const product of mockProducts) {
  const features = mockProductFeatures[product.id];
  if (features) product.features = features;
}

// ---------------------------------------------------------------------------
// Comparisons
// ---------------------------------------------------------------------------

export const mockComparisons: Comparison[] = [
  {
    id: "cmp-aws-vs-gcp",
    slug: "aws-vs-google-cloud",
    title: "AWS vs Google Cloud",
    comparison_type: "provider_vs_provider",
    provider_ids: ["aws", "google-cloud"],
    category_id: null,
    description: "Compare AWS and Google Cloud across compute, AI capabilities, credits and support.",
    rows: [
      { feature: "Compute options", values: { aws: "EC2 instance families across general, compute and memory-optimized types", "google-cloud": "Compute Engine machine families across general, compute and memory-optimized types" } },
      { feature: "AI / ML platform", values: { aws: "SageMaker, Bedrock (availability varies by account)", "google-cloud": "Vertex AI" } },
      { feature: "Credits available via GoCloudShop", values: { aws: "$1K – $100K", "google-cloud": "$300 – $25K" } },
      { feature: "Global regions", values: { aws: "Yes", "google-cloud": "Yes" } },
      { feature: "Free trial account available", values: { aws: "Yes", "google-cloud": "No (credit-based access)" } },
    ],
    seo_title: "AWS vs Google Cloud — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare AWS and Google Cloud accounts, credits and AI capabilities available through GoCloudShop.",
    is_active: true,
    sort_order: 1,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-aws-vs-azure",
    slug: "aws-vs-azure",
    title: "AWS vs Azure",
    comparison_type: "provider_vs_provider",
    provider_ids: ["aws", "azure"],
    category_id: null,
    description: "Compare AWS and Microsoft Azure across compute, AI capabilities, credits and support.",
    rows: [
      { feature: "Compute options", values: { aws: "EC2 instance families", azure: "Azure Virtual Machines" } },
      { feature: "AI / ML platform", values: { aws: "SageMaker, Bedrock (availability varies by account)", azure: "Azure AI Foundry / Cognitive Services" } },
      { feature: "Credits available via GoCloudShop", values: { aws: "$1K – $100K", azure: "$1K – $25K" } },
      { feature: "Free trial account available", values: { aws: "Yes", azure: "Yes" } },
      { feature: "Pay-as-you-go account available", values: { aws: "Via credits/compute accounts", azure: "Yes, dedicated PAYG account" } },
    ],
    seo_title: "AWS vs Azure — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare AWS and Microsoft Azure accounts, credits and AI capabilities available through GoCloudShop.",
    is_active: true,
    sort_order: 2,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-aws-vs-do",
    slug: "aws-vs-digitalocean",
    title: "AWS vs DigitalOcean",
    comparison_type: "provider_vs_provider",
    provider_ids: ["aws", "digitalocean"],
    category_id: null,
    description: "Compare AWS and DigitalOcean for compute-focused cloud accounts.",
    rows: [
      { feature: "Compute options", values: { aws: "EC2 instance families across many sizes", digitalocean: "Droplet-capacity tiers" } },
      { feature: "Best suited for", values: { aws: "Broad enterprise and AI/ML workloads", digitalocean: "Developer-focused, straightforward compute deployment" } },
      { feature: "Credits available via GoCloudShop", values: { aws: "$1K – $100K", digitalocean: "Not offered as credits — compute-capacity accounts" } },
    ],
    seo_title: "AWS vs DigitalOcean — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare AWS and DigitalOcean accounts available through GoCloudShop.",
    is_active: true,
    sort_order: 3,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-gcp-vs-azure",
    slug: "google-cloud-vs-azure",
    title: "Google Cloud vs Azure",
    comparison_type: "provider_vs_provider",
    provider_ids: ["google-cloud", "azure"],
    category_id: null,
    description: "Compare Google Cloud and Microsoft Azure across credits, AI platforms and support.",
    rows: [
      { feature: "AI / ML platform", values: { "google-cloud": "Vertex AI", azure: "Azure AI Foundry / Cognitive Services" } },
      { feature: "Credits available via GoCloudShop", values: { "google-cloud": "$300 – $25K", azure: "$1K – $25K" } },
      { feature: "Free trial account available", values: { "google-cloud": "No (credit-based access)", azure: "Yes" } },
    ],
    seo_title: "Google Cloud vs Azure — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare Google Cloud and Microsoft Azure accounts and credits available through GoCloudShop.",
    is_active: true,
    sort_order: 4,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-do-vs-linode",
    slug: "digitalocean-vs-linode",
    title: "DigitalOcean vs Linode",
    comparison_type: "provider_vs_provider",
    provider_ids: ["digitalocean", "linode"],
    category_id: null,
    description: "Compare DigitalOcean and Linode for developer-focused cloud accounts.",
    rows: [
      { feature: "Pricing model via GoCloudShop", values: { digitalocean: "Droplet-capacity tiers", linode: "Credit packages and specialized accounts" } },
      { feature: "Best suited for", values: { digitalocean: "Straightforward compute deployment", linode: "Credit-based flexible usage" } },
    ],
    seo_title: "DigitalOcean vs Linode — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare DigitalOcean and Linode accounts available through GoCloudShop.",
    is_active: true,
    sort_order: 5,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-oracle-vs-aws",
    slug: "oracle-cloud-vs-aws",
    title: "Oracle Cloud vs AWS",
    comparison_type: "provider_vs_provider",
    provider_ids: ["oracle-cloud", "aws"],
    category_id: null,
    description: "Compare Oracle Cloud Infrastructure and AWS accounts and credits.",
    rows: [
      { feature: "Credits available via GoCloudShop", values: { "oracle-cloud": "$300", aws: "$1K – $100K" } },
      { feature: "Account tiers available", values: { "oracle-cloud": "Aged, Upgraded", aws: "Free Trial, Compute (6 tiers), AI (7 products)" } },
    ],
    seo_title: "Oracle Cloud vs AWS — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare Oracle Cloud and AWS accounts and credits available through GoCloudShop.",
    is_active: true,
    sort_order: 6,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-ibm-vs-aws",
    slug: "ibm-cloud-vs-aws",
    title: "IBM Cloud vs AWS",
    comparison_type: "provider_vs_provider",
    provider_ids: ["ibm-cloud", "aws"],
    category_id: null,
    description: "Compare IBM Cloud and AWS accounts, including AI and Kubernetes access.",
    rows: [
      { feature: "AI platform", values: { "ibm-cloud": "Watson AI", aws: "SageMaker, Bedrock (availability varies)" } },
      { feature: "Kubernetes access", values: { "ibm-cloud": "Yes (via free trial)", aws: "Via applicable account configuration" } },
    ],
    seo_title: "IBM Cloud vs AWS — Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare IBM Cloud and AWS accounts available through GoCloudShop.",
    is_active: true,
    sort_order: 7,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-ai-cloud-providers",
    slug: "ai-cloud-providers",
    title: "AI Cloud Provider Comparison",
    comparison_type: "topic",
    provider_ids: ["aws", "google-cloud", "azure"],
    category_id: "cat-ai-cloud",
    description: "Compare AI-ready cloud account options across AWS, Google Cloud and Azure.",
    rows: [
      { feature: "AI-ready accounts available", values: { aws: "7 dedicated AI account products", "google-cloud": "AI-tagged credit tiers (from $1K)", azure: "AI-ready credit and infrastructure options" } },
      { feature: "Aged/established AI accounts", values: { aws: "Yes (multi-year aged tiers)", "google-cloud": "Not currently offered", azure: "Not currently offered" } },
    ],
    seo_title: "AI Cloud Provider Comparison | GoCloudShop",
    seo_description: "Compare AI-ready cloud accounts across AWS, Google Cloud and Azure.",
    is_active: true,
    sort_order: 8,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-gpu-cloud-providers",
    slug: "gpu-cloud-providers",
    title: "GPU Cloud Comparison",
    comparison_type: "topic",
    provider_ids: ["aws", "google-cloud", "azure"],
    category_id: "cat-gpu-cloud",
    description: "GPU cloud availability across supported providers.",
    rows: [
      { feature: "Dedicated GPU account products", values: { aws: "Not currently listed — contact support for availability", "google-cloud": "Not currently listed — contact support for availability", azure: "Not currently listed — contact support for availability" } },
    ],
    seo_title: "GPU Cloud Comparison | GoCloudShop",
    seo_description: "Compare GPU cloud availability across GoCloudShop's supported providers.",
    is_active: true,
    sort_order: 9,
    created_at: now,
    updated_at: now,
  },
  {
    id: "cmp-cloud-credit-comparison",
    slug: "cloud-credit-comparison",
    title: "Cloud Credit Comparison",
    comparison_type: "topic",
    provider_ids: ["aws", "google-cloud", "azure", "oracle-cloud", "linode"],
    category_id: "cat-cloud-credits",
    description: "Compare cloud credit package sizes and starting prices across every supported provider.",
    rows: [
      { feature: "Smallest credit package", values: { aws: "$1K", "google-cloud": "$300", azure: "$1K", "oracle-cloud": "$300", linode: "$100" } },
      { feature: "Largest credit package", values: { aws: "$100K", "google-cloud": "$25K", azure: "$25K", "oracle-cloud": "$300", linode: "$100" } },
    ],
    seo_title: "Cloud Credit Comparison | GoCloudShop",
    seo_description: "Compare cloud credit package sizes and prices across every supported provider.",
    is_active: true,
    sort_order: 10,
    created_at: now,
    updated_at: now,
  },
];

// ---------------------------------------------------------------------------
// Use cases
// ---------------------------------------------------------------------------

export const mockUseCases: UseCase[] = [
  { id: "uc-ai-ml", slug: "ai-machine-learning", title: "AI & Machine Learning", description: "AI-ready cloud accounts for model development, training and inference.", icon: "BrainCircuit", content: "GoCloudShop's AI Cloud category lists AI-enabled accounts across compute tiers, suited to development, experimentation and production AI/ML workloads.", related_category_ids: ["cat-ai-cloud", "cat-ai-ml"], related_product_type: null, seo_title: "AI & Machine Learning Cloud Infrastructure | GoCloudShop", seo_description: "Explore AI-ready cloud accounts for machine learning development and inference.", is_active: true, sort_order: 1, created_at: now, updated_at: now },
  { id: "uc-genai", slug: "generative-ai", title: "Generative AI", description: "Infrastructure for generative AI development and experimentation.", icon: "Sparkles", content: "AI-enabled accounts and credit packages provide the underlying compute for generative AI projects, from prototyping to scaled workloads.", related_category_ids: ["cat-ai-cloud"], related_product_type: null, seo_title: "Generative AI Cloud Infrastructure | GoCloudShop", seo_description: "Explore cloud infrastructure suited to generative AI development.", is_active: true, sort_order: 2, created_at: now, updated_at: now },
  { id: "uc-saas", slug: "saas", title: "SaaS Development", description: "Reliable compute and credits for building and scaling SaaS products.", icon: "LayoutGrid", content: "Compute accounts and cloud credits give SaaS teams flexible infrastructure to build, test and scale, without long-term provider commitments.", related_category_ids: ["cat-compute", "cat-cloud-credits"], related_product_type: null, seo_title: "Cloud Infrastructure for SaaS Development | GoCloudShop", seo_description: "Explore compute and credit options suited to SaaS development.", is_active: true, sort_order: 3, created_at: now, updated_at: now },
  { id: "uc-hosting", slug: "web-hosting", title: "Web Hosting", description: "Cloud accounts suited to hosting websites and web applications.", icon: "Globe", content: "Cloud compute accounts across providers give hosting businesses and agencies a foundation for client sites and applications.", related_category_ids: ["cat-cloud-accounts", "cat-compute"], related_product_type: null, seo_title: "Cloud Accounts for Web Hosting | GoCloudShop", seo_description: "Explore cloud accounts suited to web hosting workloads.", is_active: true, sort_order: 4, created_at: now, updated_at: now },
  { id: "uc-cloud-computing", slug: "cloud-computing", title: "Cloud Computing", description: "General-purpose cloud compute for any project.", icon: "Cloud", content: "Browse compute accounts across every supported provider, sized from lightweight development environments to large production workloads.", related_category_ids: ["cat-compute", "cat-cloud-accounts"], related_product_type: null, seo_title: "General Cloud Computing Infrastructure | GoCloudShop", seo_description: "Explore general-purpose cloud compute accounts across providers.", is_active: true, sort_order: 5, created_at: now, updated_at: now },
  { id: "uc-gpu-computing", slug: "gpu-computing", title: "GPU Computing", description: "GPU-accelerated infrastructure for compute-intensive workloads.", icon: "Cpu", content: "GoCloudShop lists GPU-tagged products as they become available; check back or contact support for current GPU cloud availability.", related_category_ids: ["cat-gpu-cloud"], related_product_type: null, seo_title: "GPU Computing Infrastructure | GoCloudShop", seo_description: "Explore GPU cloud computing options at GoCloudShop.", is_active: true, sort_order: 6, created_at: now, updated_at: now },
  { id: "uc-dev-testing", slug: "development-testing", title: "Development & Testing", description: "Affordable accounts for development and QA environments.", icon: "FlaskConical", content: "Free trial and lower compute-tier accounts are well suited to development and testing environments before production scale-up.", related_category_ids: ["cat-free-trials", "cat-compute"], related_product_type: null, seo_title: "Cloud Accounts for Development & Testing | GoCloudShop", seo_description: "Explore free trial and compute accounts suited to dev/test environments.", is_active: true, sort_order: 7, created_at: now, updated_at: now },
  { id: "uc-devops", slug: "devops", title: "DevOps", description: "Infrastructure for CI/CD pipelines and DevOps workflows.", icon: "GitBranch", content: "Compute and PAYG accounts provide flexible infrastructure for DevOps pipelines, staging environments and automation workloads.", related_category_ids: ["cat-compute", "cat-pay-as-you-go"], related_product_type: null, seo_title: "Cloud Infrastructure for DevOps | GoCloudShop", seo_description: "Explore compute and PAYG accounts suited to DevOps workflows.", is_active: true, sort_order: 8, created_at: now, updated_at: now },
  { id: "uc-kubernetes", slug: "kubernetes", title: "Kubernetes", description: "Cloud accounts with Kubernetes access for container orchestration.", icon: "Boxes", content: "IBM Cloud's free trial includes Kubernetes and OpenShift access; other providers' Kubernetes services are reachable through their standard compute accounts.", related_category_ids: ["cat-cloud-accounts"], related_product_type: null, seo_title: "Kubernetes-Ready Cloud Accounts | GoCloudShop", seo_description: "Explore cloud accounts with Kubernetes access.", is_active: true, sort_order: 9, created_at: now, updated_at: now },
  { id: "uc-data-engineering", slug: "data-engineering", title: "Data Engineering", description: "Compute and storage infrastructure for data pipelines.", icon: "Database", content: "Higher compute-tier accounts and cloud credits support data engineering workloads such as pipeline processing and warehousing.", related_category_ids: ["cat-compute", "cat-cloud-credits"], related_product_type: null, seo_title: "Cloud Infrastructure for Data Engineering | GoCloudShop", seo_description: "Explore compute and credit options suited to data engineering.", is_active: true, sort_order: 10, created_at: now, updated_at: now },
  { id: "uc-data-analytics", slug: "data-analytics", title: "Data Analytics", description: "Infrastructure for analytics and BigQuery/analytics-style workloads.", icon: "BarChart3", content: "Cloud credit packages provide budget for analytics services such as BigQuery, alongside general compute for processing pipelines.", related_category_ids: ["cat-cloud-credits"], related_product_type: null, seo_title: "Cloud Infrastructure for Data Analytics | GoCloudShop", seo_description: "Explore credit and compute options suited to data analytics.", is_active: true, sort_order: 11, created_at: now, updated_at: now },
  { id: "uc-research", slug: "research", title: "Research", description: "Flexible, low-commitment infrastructure for research projects.", icon: "Microscope", content: "Free trial accounts and smaller credit packages give researchers a low-commitment way to access cloud and AI infrastructure.", related_category_ids: ["cat-free-trials", "cat-cloud-credits"], related_product_type: null, seo_title: "Cloud Infrastructure for Research | GoCloudShop", seo_description: "Explore free trial and credit options suited to research projects.", is_active: true, sort_order: 12, created_at: now, updated_at: now },
  { id: "uc-startup", slug: "startup-infrastructure", title: "Startup Infrastructure", description: "Cost-conscious cloud infrastructure for early-stage startups.", icon: "Rocket", content: "Free trials, entry-level compute and smaller credit packages help startups get infrastructure running without large upfront spend.", related_category_ids: ["cat-free-trials", "cat-compute"], related_product_type: null, seo_title: "Cloud Infrastructure for Startups | GoCloudShop", seo_description: "Explore startup-friendly cloud accounts and credits.", is_active: true, sort_order: 13, created_at: now, updated_at: now },
  { id: "uc-enterprise", slug: "enterprise-infrastructure", title: "Enterprise Infrastructure", description: "Large-scale cloud and AI infrastructure for enterprise teams.", icon: "Building2", content: "Enterprise-tier credits and AI accounts provide large-scale cloud usage with enterprise billing environments.", related_category_ids: ["cat-enterprise"], related_product_type: null, seo_title: "Enterprise Cloud Infrastructure | GoCloudShop", seo_description: "Explore enterprise-scale cloud accounts, credits and AI infrastructure.", is_active: true, sort_order: 14, created_at: now, updated_at: now },
];

// ---------------------------------------------------------------------------
// Guides
// ---------------------------------------------------------------------------

export const mockGuides: Guide[] = [
  { id: "g-cloud-buying-guide", slug: "cloud-account-buying-guide", title: "Cloud Account Buying Guide", excerpt: "What to check before buying a cloud account: provider, specs, region, delivery and support.", content: "## What to check before buying\n\nBefore choosing a cloud account, review the provider, compute specifications, region availability, delivery time and support type listed on the product page. Every GoCloudShop listing shows these details before you order.\n\n## Matching an account to your project\n\nStart from your workload's needs (compute, storage, AI capability) and use the category and filter pages to narrow down providers and tiers rather than starting from price alone.\n\n## Ordering\n\nOnce you've selected a product and variation, use the **Order via Telegram** button to contact support with your exact selection pre-filled.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-cloud-accounts", tags: ["buying-guide", "cloud-accounts"], status: "published", published_at: now, seo_title: "Cloud Account Buying Guide | GoCloudShop", seo_description: "Learn what to check before buying a cloud account, from specifications to delivery and support.", created_at: now, updated_at: now },
  { id: "g-credit-buying-guide", slug: "cloud-credit-buying-guide", title: "Cloud Credit Buying Guide", excerpt: "How cloud credit packages work and how to choose the right size.", content: "## How cloud credits work\n\nCloud credit packages provide prepaid usage value on a provider's platform. GoCloudShop lists credit packages across AWS, Google Cloud, Azure, Oracle Cloud and Linode in a range of sizes.\n\n## Choosing a package size\n\nCompare package sizes on the [Cloud Credit Comparison](/compare/cloud-credit-comparison) page, and check each listing's specifications for the exact credit amount and any provider-specific limitations before ordering.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-cloud-credits", tags: ["buying-guide", "credits"], status: "published", published_at: now, seo_title: "Cloud Credit Buying Guide | GoCloudShop", seo_description: "Learn how cloud credit packages work and how to choose the right size for your project.", created_at: now, updated_at: now },
  { id: "g-ai-cloud-guide", slug: "ai-cloud-guide", title: "AI Cloud Guide", excerpt: "An overview of AI-ready cloud accounts and what to look for.", content: "## What makes an account AI-ready\n\nAI-ready accounts on GoCloudShop are flagged `AI Enabled` and list AI-specific details such as request-per-minute capacity, compute tier and support level directly on the product page.\n\n## Choosing between AI account tiers\n\nCompare request capacity, vCPU and support rating across the AI Cloud category page before ordering, and check the **AI Specifications** section on each product page for the exact details configured for that listing.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-ai-cloud", tags: ["ai-cloud", "guide"], status: "published", published_at: now, seo_title: "AI Cloud Guide | GoCloudShop", seo_description: "An overview of AI-ready cloud accounts and how to choose between tiers.", created_at: now, updated_at: now },
  { id: "g-gpu-cloud-guide", slug: "gpu-cloud-guide", title: "GPU Cloud Guide", excerpt: "What to know about GPU cloud infrastructure availability.", content: "## GPU cloud at GoCloudShop\n\nGPU-tagged products are flagged with `is_gpu` and appear in the GPU Cloud category automatically as they're added to the catalog. Check the GPU Cloud page or contact support for current availability.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-gpu-cloud", tags: ["gpu", "guide"], status: "published", published_at: now, seo_title: "GPU Cloud Guide | GoCloudShop", seo_description: "What to know about GPU cloud infrastructure availability at GoCloudShop.", created_at: now, updated_at: now },
  { id: "g-provider-guide", slug: "cloud-provider-guide", title: "Cloud Provider Guide", excerpt: "An overview of every provider supported on GoCloudShop.", content: "## Supported providers\n\nGoCloudShop lists accounts and credits from AWS, Google Cloud, Azure, DigitalOcean, Oracle Cloud, Linode, IBM Cloud, Kamatera, Alibaba Cloud and Atlantic.Net. Visit each [provider page](/providers) for its full product catalog, description and starting price.", cover_image_url: null, guide_type: "provider_guide", related_provider_id: null, related_category_id: null, tags: ["providers"], status: "published", published_at: now, seo_title: "Cloud Provider Guide | GoCloudShop", seo_description: "An overview of every cloud provider supported on GoCloudShop.", created_at: now, updated_at: now },
  { id: "g-pricing-guide", slug: "cloud-pricing-guide", title: "Cloud Pricing Guide", excerpt: "How pricing works across GoCloudShop's catalog.", content: "## How pricing works\n\nEvery price shown on GoCloudShop comes directly from our product database and is kept current by our team. Products with multiple tiers (variations) show a starting \"from\" price on listing pages; select a variation on the product page to see its exact price.\n\nPrices do not include any third-party provider billing that may apply after account setup — check each listing's **Before You Order** section for details.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: null, tags: ["pricing"], status: "published", published_at: now, seo_title: "Cloud Pricing Guide | GoCloudShop", seo_description: "Understand how pricing works across GoCloudShop's cloud and AI product catalog.", created_at: now, updated_at: now },
  { id: "g-ai-infra-guide", slug: "ai-infrastructure-guide", title: "AI Infrastructure Guide", excerpt: "Planning cloud infrastructure for AI workloads.", content: "## Planning AI infrastructure\n\nAI workloads vary widely in compute and support needs. Review each AI product's compute tier, request-per-minute capacity and support rating, and use the [AI Cloud Provider Comparison](/compare/ai-cloud-providers) to compare options across providers before ordering.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-ai-cloud", tags: ["ai", "infrastructure"], status: "published", published_at: now, seo_title: "AI Infrastructure Guide | GoCloudShop", seo_description: "Guidance on planning cloud infrastructure for AI workloads.", created_at: now, updated_at: now },
  { id: "g-setup-guide", slug: "cloud-account-setup-guide", title: "Cloud Account Setup Guide", excerpt: "What happens after you order a cloud account.", content: "## After you order\n\nOnce you contact support via Telegram with your selected product and variation, our team confirms availability and order details, processes payment, then delivers access information. See [How It Works](/how-it-works) for the full step-by-step flow.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: null, tags: ["setup"], status: "published", published_at: now, seo_title: "Cloud Account Setup Guide | GoCloudShop", seo_description: "What to expect after ordering a cloud account from GoCloudShop.", created_at: now, updated_at: now },
  { id: "g-security-guide", slug: "cloud-security-guide", title: "Cloud Security Guide", excerpt: "Security practices to follow after receiving a cloud account.", content: "## After delivery\n\nOnce you receive access to a cloud account, we recommend immediately rotating any shared credentials, enabling multi-factor authentication where the provider supports it, and reviewing the provider's own security documentation for the services you plan to use.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: null, tags: ["security"], status: "published", published_at: now, seo_title: "Cloud Security Guide | GoCloudShop", seo_description: "Security practices to follow after receiving a cloud account from GoCloudShop.", created_at: now, updated_at: now },
  { id: "g-cost-optimization", slug: "cloud-cost-optimization-guide", title: "Cloud Cost Optimization Guide", excerpt: "Tips for getting more value from cloud credits and compute accounts.", content: "## Getting the most from your credits\n\nMonitor usage against your credit balance regularly through the provider's own billing dashboard, right-size compute tiers to actual workload demand, and shut down unused resources between work sessions.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-cloud-credits", tags: ["cost-optimization"], status: "published", published_at: now, seo_title: "Cloud Cost Optimization Guide | GoCloudShop", seo_description: "Tips for getting more value from cloud credits and compute accounts.", created_at: now, updated_at: now },
  { id: "g-ai-planning-guide", slug: "ai-infrastructure-planning-guide", title: "AI Infrastructure Planning Guide", excerpt: "How to plan compute capacity for an AI project.", content: "## Planning compute capacity\n\nEstimate your AI workload's request volume and compute needs before selecting a tier — GoCloudShop's AI accounts range from 10 RPM/32 vCPU starter tiers up to enterprise-scale 384 vCPU accounts. Start smaller and scale up as usage grows.", cover_image_url: null, guide_type: "guide", related_provider_id: null, related_category_id: "cat-ai-cloud", tags: ["ai", "planning"], status: "published", published_at: now, seo_title: "AI Infrastructure Planning Guide | GoCloudShop", seo_description: "How to plan cloud compute capacity for an AI project.", created_at: now, updated_at: now },

  // -- Stock Updates — dated stock-availability announcements. Same guides
  // table/architecture as the rest of this array (guide_type: "stock_update"),
  // with the additive price/currency/availability columns populated. See
  // src/lib/data/guides.ts (getStockUpdates) and /stock-updates.
  {
    id: "su-azure-gpt5-credit",
    slug: "azure-1000-credit-gpt5-mini-working",
    title: "Azure Account with $1000 Credit — OpenAI GPT-5 Mini Working",
    excerpt: "A Microsoft Azure account with $1,000 in credit and confirmed working access to OpenAI GPT-5 Mini through Azure OpenAI Service.",
    content:
      "## What's included\n\n- $1,000 Azure credit balance\n- Confirmed working access to OpenAI GPT-5 Mini via Azure OpenAI Service\n- Active billing, identity and phone verification already complete\n- Clean account history\n\nThis is a limited batch — once sold out, the next confirmed batch will be posted here.",
    cover_image_url: null,
    guide_type: "stock_update",
    related_provider_id: "azure",
    related_category_id: "cat-ai-cloud",
    tags: ["Premium Stock", "AI Enabled", "Credit-Loaded"],
    status: "published",
    published_at: "2026-08-13T09:00:00.000Z",
    seo_title: "Azure Account with $1000 Credit — GPT-5 Mini Working | GoCloudShop Stock Updates",
    seo_description: "Limited-availability Azure account with $1,000 credit and confirmed OpenAI GPT-5 Mini access via Azure OpenAI Service.",
    price: 249,
    currency: "USD",
    availability: "limited",
    created_at: now,
    updated_at: now,
  },
  {
    id: "su-aws-bedrock-opus",
    slug: "aws-512vcpu-bedrock-claude-opus",
    title: "AWS AI Account — 512 vCPU, Bedrock Claude Opus Ready",
    excerpt: "A high-compute, multi-year aged AWS account with Amazon Bedrock pre-enabled for Claude Opus and 512 vCPU of capacity.",
    content:
      "## What's included\n\n- 512 vCPU compute capacity\n- Amazon Bedrock enabled with Claude Opus access\n- Multi-year aged account history\n- Pre-raised service limits\n\nIdeal for production-scale generative AI workloads that need both compute headroom and model access already approved.",
    cover_image_url: null,
    guide_type: "stock_update",
    related_provider_id: "aws",
    related_category_id: "cat-ai-cloud",
    tags: ["Premium Stock", "AI Enabled", "Aged Account"],
    status: "published",
    published_at: "2026-08-12T09:00:00.000Z",
    seo_title: "AWS AI Account — 512 vCPU, Bedrock Claude Opus Ready | GoCloudShop Stock Updates",
    seo_description: "High-compute AWS account with Amazon Bedrock Claude Opus access pre-enabled and 512 vCPU of capacity.",
    price: 1499,
    currency: "USD",
    availability: "limited",
    created_at: now,
    updated_at: now,
  },
  {
    id: "su-gcp-vertex-gemini",
    slug: "google-cloud-5k-credit-vertex-gemini-ultra",
    title: "Google Cloud Account — $5K Credit, Vertex AI Gemini Ultra Enabled",
    excerpt: "A Google Cloud account with $5,000 in credit and Vertex AI configured for Gemini Ultra access.",
    content:
      "## What's included\n\n- $5,000 Google Cloud credit balance\n- Vertex AI enabled with Gemini Ultra access\n- Fully verified billing and identity\n- Clean account history\n\nA strong option for teams building on Gemini Ultra without waiting on Vertex AI quota approvals.",
    cover_image_url: null,
    guide_type: "stock_update",
    related_provider_id: "google-cloud",
    related_category_id: "cat-ai-cloud",
    tags: ["Premium Stock", "AI Enabled", "Credit-Loaded"],
    status: "published",
    published_at: "2026-08-11T09:00:00.000Z",
    seo_title: "Google Cloud Account — $5K Credit, Vertex AI Gemini Ultra | GoCloudShop Stock Updates",
    seo_description: "Google Cloud account with $5,000 credit and Vertex AI Gemini Ultra access already enabled.",
    price: 899,
    currency: "USD",
    availability: "in_stock",
    created_at: now,
    updated_at: now,
  },
  {
    id: "su-oracle-aged-tenancy",
    slug: "oracle-cloud-multi-year-aged-tenancy",
    title: "Oracle Cloud — Multi-Year Aged Tenancy, Always Free Unlocked",
    excerpt: "An Oracle Cloud Infrastructure tenancy with multi-year account history and Always Free resources unlocked.",
    content:
      "## What's included\n\n- 2+ years of clean tenancy history\n- Always Free resources (Ampere A1 ARM, block storage) unlocked\n- Higher initial service limits\n- Verified billing\n\nSuited to long-running workloads where account stability and established history matter.",
    cover_image_url: null,
    guide_type: "stock_update",
    related_provider_id: "oracle-cloud",
    related_category_id: "cat-cloud-accounts",
    tags: ["Premium Stock", "Aged Account"],
    status: "published",
    published_at: "2026-08-10T09:00:00.000Z",
    seo_title: "Oracle Cloud — Multi-Year Aged Tenancy | GoCloudShop Stock Updates",
    seo_description: "Multi-year aged Oracle Cloud tenancy with Always Free resources unlocked and higher service limits.",
    price: 349,
    currency: "USD",
    availability: "in_stock",
    created_at: now,
    updated_at: now,
  },
  {
    id: "su-linode-port25",
    slug: "linode-port-25-open-high-traffic",
    title: "Linode Account — Port 25 Open, High-Traffic Ready",
    excerpt: "A Linode account configured with Port 25 open for email infrastructure and sized for high-traffic workloads.",
    content:
      "## What's included\n\n- Port 25 open — no restrictions on outbound SMTP\n- Sized for high-traffic email/web workloads\n- Verified billing and clean history\n\nThis batch has now sold out — check back for the next confirmed restock.",
    cover_image_url: null,
    guide_type: "stock_update",
    related_provider_id: "linode",
    related_category_id: "cat-cloud-accounts",
    tags: ["Premium Stock", "Port 25 Open"],
    status: "published",
    published_at: "2026-08-08T09:00:00.000Z",
    seo_title: "Linode Account — Port 25 Open, High-Traffic Ready | GoCloudShop Stock Updates",
    seo_description: "Linode account with Port 25 open for email infrastructure, sized for high-traffic workloads.",
    price: 129,
    currency: "USD",
    availability: "out_of_stock",
    created_at: now,
    updated_at: now,
  },
];

// ---------------------------------------------------------------------------
// FAQs (global) — spec §38, business-policy-driven answers
// ---------------------------------------------------------------------------

export const mockFaqs: Faq[] = [
  { id: "faq-1", question: "What does GoCloudShop offer?", answer: "GoCloudShop is a cloud and AI infrastructure marketplace offering cloud accounts, cloud credits, AI-ready accounts and compute solutions from multiple providers, each listed with transparent pricing and specifications.", product_id: null, provider_id: null, category: "General", sort_order: 1, is_active: true, created_at: now, updated_at: now },
  { id: "faq-2", question: "What is an AI Cloud product?", answer: "An AI Cloud product is a cloud account configured and flagged as AI-enabled — suited to AI development, experimentation or production workloads. Each AI product page lists its specific AI specifications, such as request capacity and compute tier.", product_id: null, provider_id: null, category: "General", sort_order: 2, is_active: true, created_at: now, updated_at: now },
  { id: "faq-3", question: "Which providers are available?", answer: "GoCloudShop currently lists AWS, Google Cloud, Microsoft Azure, DigitalOcean, Oracle Cloud, Linode, IBM Cloud, Kamatera, Alibaba Cloud and Atlantic.Net. Browse all providers on the Providers page.", product_id: null, provider_id: null, category: "General", sort_order: 3, is_active: true, created_at: now, updated_at: now },
  { id: "faq-4", question: "How do I order?", answer: "Select a product and variation, review the price and specifications, then use the \"Order via Telegram\" button. This opens a pre-filled message to our support team with your selected product, variation and price.", product_id: null, provider_id: null, category: "Ordering", sort_order: 4, is_active: true, created_at: now, updated_at: now },
  { id: "faq-5", question: "How quickly is an order processed?", answer: "Processing time depends on the specific product's configured delivery time, shown on its product page. Our support team confirms availability and order details with you via Telegram before delivery.", product_id: null, provider_id: null, category: "Ordering", sort_order: 5, is_active: true, created_at: now, updated_at: now },
  { id: "faq-6", question: "What payment methods are supported?", answer: "Payment methods are confirmed directly with our support team via Telegram during order confirmation, since accepted methods can vary by product and region.", product_id: null, provider_id: null, category: "Ordering", sort_order: 6, is_active: true, created_at: now, updated_at: now },
  { id: "faq-7", question: "Do products have replacement policies?", answer: "Where configured, a product's replacement policy is shown in its Before You Order section. Not every product has the same policy, so check the specific listing before ordering.", product_id: null, provider_id: null, category: "Policies", sort_order: 7, is_active: true, created_at: now, updated_at: now },
  { id: "faq-8", question: "Do products have refund policies?", answer: "Where configured, a product's refund policy is shown in its Before You Order section. See our Refund Policy page for our general terms.", product_id: null, provider_id: null, category: "Policies", sort_order: 8, is_active: true, created_at: now, updated_at: now },
  { id: "faq-9", question: "Can I compare products?", answer: "Yes. Use the Compare section to view side-by-side provider and product comparisons across compute, pricing, AI capabilities and more.", product_id: null, provider_id: null, category: "General", sort_order: 9, is_active: true, created_at: now, updated_at: now },
  { id: "faq-10", question: "Do you offer AI/GPU products?", answer: "Yes, AI-ready accounts are available now under AI Cloud. GPU-tagged products appear automatically in the GPU Cloud category as they're added to the catalog — check that page or contact support for current availability.", product_id: null, provider_id: null, category: "General", sort_order: 10, is_active: true, created_at: now, updated_at: now },
  { id: "faq-11", question: "How can I contact support?", answer: "The fastest way to reach us is via Telegram — use the \"Contact Support\" or \"Order via Telegram\" buttons found throughout the site.", product_id: null, provider_id: null, category: "General", sort_order: 11, is_active: true, created_at: now, updated_at: now },
];

// ---------------------------------------------------------------------------
// Reviews — none seeded (spec forbids fabricated reviews)
// ---------------------------------------------------------------------------

export const mockReviews: Review[] = [];

// ---------------------------------------------------------------------------
// Site settings
// ---------------------------------------------------------------------------

export const mockSiteSettings: SiteSettings = {
  id: 1,
  site_name: "GoCloudShop",
  tagline: "Cloud Access. Simplified.",
  logo_url: null,
  favicon_url: null,
  telegram_username: "GoCloudShopSupport",
  // Real number provided by the site owner (+1 (404) 203-0453), stored
  // digits-only per the ContactChannels convention.
  whatsapp_number: "14042030453",
  // Real channel URL provided by the site owner.
  telegram_channel_url: "https://t.me/cloudaccountstock",
  support_email: "hellogocloudshop@gmail.com",
  social_links: {},
  footer_content: {},
  default_seo: {
    title: "GoCloudShop — Cloud Accounts & AI Cloud, Made Simple",
    description:
      "Explore cloud accounts, AI-ready infrastructure, cloud credits and compute solutions from multiple providers — with clear pricing, detailed specifications and responsive support.",
  },
  privacy_policy: "GoCloudShop collects only the information you provide when contacting support or subscribing to updates. We do not sell customer data to third parties.",
  terms_of_service: "By ordering through GoCloudShop, you agree to the pricing, specifications and policies listed on the relevant product page at the time of order.",
  refund_policy: "Refund eligibility is evaluated case-by-case and, where applicable, is stated on the specific product's page. Contact support via Telegram to request a refund review.",
  disclaimer: "GoCloudShop is an independent marketplace. Product listings are not officially endorsed by the referenced cloud providers unless explicitly stated on the listing.",
  updated_at: now,
};

export function getMockProductWithRelations(id: string): Product | undefined {
  const product = mockProducts.find((p) => p.id === id);
  if (!product) return undefined;
  return {
    ...product,
    provider: product.provider_id ? prov(mockProviders.find((p) => p.id === product.provider_id)?.slug ?? "") : null,
    category: product.category_id ? mockCategories.find((c) => c.id === product.category_id) ?? null : null,
    variations: mockVariations.filter((v) => v.product_id === product.id),
  };
}

export { cat as mockCategoryBySlug, prov as mockProviderBySlug };
