/**
 * Homepage-only marketing descriptions for the "Cloud Account Categories"
 * section — presentation-only content, keyed by provider.slug, following the
 * same override-map pattern as cloudServiceDisplay.ts and
 * providerAccountUrls.ts. Deliberately NOT written into `providers.description`
 * in the database, since that field is used sitewide (provider pages,
 * Cloud-Service cards, SEO) and this copy is specifically the full-length
 * marketing paragraph supplied for the Homepage. A provider with no entry
 * here simply falls back to its real `provider.description` from the
 * database — nothing breaks if a new provider is added later (e.g.
 * Atlantic.Net, which isn't part of the Homepage's nine-provider copy but
 * keeps its own real description and stays fully linked/functional).
 */
export const HOMEPAGE_PROVIDER_COPY: Record<string, string> = {
  aws: "AWS remains the most widely adopted cloud platform, offering comprehensive compute, storage, and AI/ML services. When you Buy AWS Account through our marketplace, you gain access to verified infrastructure with pre-enabled services including EC2, S3, Lambda, and Amazon Bedrock. We offer standard accounts, aged accounts with established history, AI-enabled configurations, and credit-loaded packages from $1K to $100K. AWS is ideal for enterprises, startups, and developers building scalable applications on the world's most mature cloud ecosystem.",
  "google-cloud": "Google Cloud excels in data analytics, machine learning, and containerized workloads. Buy Google Cloud Accounts to access BigQuery, Vertex AI, Kubernetes Engine, and Cloud Run with verified billing already attached. Our GCP options include credit packages ranging from $300 to $25K, standard verified accounts, and configurations suitable for both development and production environments. Google Cloud's global network and AI capabilities make it a strong choice for data-driven organizations.",
  azure: "Azure provides enterprise-grade infrastructure with seamless integration for Windows workloads and Microsoft ecosystems. Buy Microsoft Azure Accounts to deploy Virtual Machines, Azure Kubernetes Service, and Azure OpenAI services with pre-verified billing and identity. Our Azure catalog includes cloud credit packages from $1K to $25K, pay-as-you-go accounts, and free trial options. Azure is particularly suitable for organizations already using Microsoft technologies or requiring hybrid cloud solutions.",
  digitalocean: "DigitalOcean is known for its simplicity, predictable pricing, and developer-friendly interface. Buy DigitalOcean Accounts to access scalable Droplets, managed Kubernetes, and object storage without the complexity of larger cloud providers. Our offerings include compute accounts with 3 to 10 droplet capacity and port-25-open accounts for email server deployments. DigitalOcean is an excellent choice for startups, independent developers, and small to medium businesses seeking straightforward cloud infrastructure.",
  "oracle-cloud": "Oracle Cloud offers enterprise-performance with competitive pricing and one of the industry's most generous free tiers. Buy Oracle Cloud Accounts to access Ampere A1 ARM instances with up to 4 CPU cores and 24 GB RAM, Autonomous Database, and Oracle Kubernetes Engine. Our OCI options include $300 credit accounts, aged tenancies with established history, and upgraded accounts with pre-raised service limits. Oracle Cloud is well-suited for mission-critical workloads and organizations seeking cost-effective enterprise infrastructure.",
  linode: "Linode delivers reliable, affordable VPS hosting with a global network of data centers. Buy Linode Accounts to deploy virtual private servers, Kubernetes clusters, and object storage with straightforward pricing. Our Linode offerings include $100 credit accounts valid for 60 days and port-25-open configurations for email server operations. Linode is popular among developers, agencies, and businesses seeking uncomplicated, cost-effective cloud infrastructure.",
  "ibm-cloud": "IBM Cloud combines enterprise infrastructure with powerful AI capabilities through watsonx and managed Kubernetes. Buy IBM Cloud Accounts to access Virtual Private Cloud, Red Hat OpenShift, and 40+ always-free products. Our IBM Cloud options include free trial accounts with $200 in credits and standard accounts suitable for development and production workloads. IBM Cloud is particularly valuable for organizations building AI solutions and those requiring enterprise-grade security and compliance.",
  kamatera: "Kamatera provides enterprise-class VPS hosting with flexible pricing, pay-per-second billing, and a global data center footprint. Buy Kamatera Accounts to deploy virtual dedicated servers with dedicated CPU cores and guaranteed RAM allocation. Our Kamatera offerings include free trial accounts with $100 in server configuration and 1 TB of traffic. Kamatera's unrestricted port 25 policy makes it an excellent choice for businesses running email servers and transactional email services.",
  "alibaba-cloud": "Alibaba Cloud is Asia's largest cloud provider, offering extensive infrastructure with strong coverage across the Asia-Pacific region. Buy Alibaba Cloud Accounts to access Elastic Compute Service, Object Storage Service, and Kubernetes Container Service. Our Alibaba Cloud options include Personal accounts for individual developers and Business accounts for organizations, both with verification already completed. Alibaba Cloud is ideal for businesses targeting Asian markets or requiring robust infrastructure in the region.",
  "atlantic-net": "Atlantic.Net has been a trusted name in cloud hosting since 1994, offering HIPAA-compliant hosting and a generous 1-year free trial. Get started with a verified Atlantic account and deploy your projects in minutes.",
};
